import bcrypt from "bcryptjs";

const SECRET = "DOAFFAIRE-REST-API";

//creates an HMAC (Hash-based Message Authentication Code) object using the SHA-256
export const authentication = (salt, password) => {
  return bcrypt
    .createHmac("sha256", [salt, password].join("/"))
    .update(SECRET)
    .digest("hex");
};

// performing authentication using cryptographic operations
export const random = () => bcrypt.randomBytes(128).toString("base64"); // generates 128 random bytes using a cryptographic pseudorandom number generator, converts the generated bytes into a base64-encoded string.

export const comparePassword = (password, encryptedPassword) => {
  bcrypt.compare(password, encryptedPassword, (error, isMatch) => {
    if (error) {
      return error;
    } else {
      return isMatch;
    }
  });
};
